# Feature: source-viability-spikes, Property 1: URL Validation Rejects All Non-Authorized Endpoints
"""Property-based tests for TMDB URL validation.

Validates: Requirements 1.1, 1.6

For any URL string, the TMDB URL validator SHALL accept it if and only if it exactly
matches the pattern `https://api.themoviedb.org/3/trending/movie/(day|week)`. All other
URL strings SHALL be rejected.
"""

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from spikes.tmdb.validators import build_tmdb_url, validate_tmdb_url

# The only two URLs that should ever pass validation
VALID_URLS = frozenset(
    [
        "https://api.themoviedb.org/3/trending/movie/day",
        "https://api.themoviedb.org/3/trending/movie/week",
    ]
)


@pytest.mark.property
@settings(max_examples=100)
@given(text=st.text())
def test_random_strings_are_rejected(text: str) -> None:
    """Random strings generated by st.text() are never accepted as valid URLs.

    The probability of hypothesis generating one of the exact two valid URLs from
    the full unicode text space is negligible, so we explicitly exclude them.
    """
    if text in VALID_URLS:
        return  # Skip the exact valid URLs if hypothesis generates them
    assert validate_tmdb_url(text) is False


@pytest.mark.property
@settings(max_examples=100)
@given(time_window=st.sampled_from(["day", "week"]))
def test_valid_urls_built_with_build_tmdb_url_are_accepted(time_window: str) -> None:
    """Valid URLs built with build_tmdb_url are always accepted by the validator."""
    url = build_tmdb_url(time_window)
    assert validate_tmdb_url(url) is True
    assert url in VALID_URLS


@pytest.mark.property
@settings(max_examples=100)
@given(
    time_window=st.sampled_from(["day", "week"]),
    extra_segment=st.text(min_size=1).filter(lambda s: "/" not in s and s.strip()),
)
def test_extra_path_segments_are_rejected(time_window: str, extra_segment: str) -> None:
    """URLs with extra path segments appended are rejected."""
    base_url = f"https://api.themoviedb.org/3/trending/movie/{time_window}"
    url_with_extra = f"{base_url}/{extra_segment}"
    assert validate_tmdb_url(url_with_extra) is False


@pytest.mark.property
@settings(max_examples=100)
@given(
    time_window=st.sampled_from(["day", "week"]),
    param_key=st.text(
        alphabet=st.characters(whitelist_categories=("L", "N")), min_size=1
    ),
    param_value=st.text(
        alphabet=st.characters(whitelist_categories=("L", "N")), min_size=1
    ),
)
def test_query_params_are_rejected(
    time_window: str, param_key: str, param_value: str
) -> None:
    """URLs with query parameters are rejected."""
    base_url = f"https://api.themoviedb.org/3/trending/movie/{time_window}"
    url_with_params = f"{base_url}?{param_key}={param_value}"
    assert validate_tmdb_url(url_with_params) is False


@pytest.mark.property
@settings(max_examples=100)
@given(
    domain=st.sampled_from(
        [
            "http://api.themoviedb.org",
            "https://evil.themoviedb.org",
            "https://api.tmdb.org",
            "https://api.themoviedb.com",
            "https://themoviedb.org",
            "ftp://api.themoviedb.org",
        ]
    ),
    time_window=st.sampled_from(["day", "week"]),
)
def test_different_domains_or_protocols_are_rejected(
    domain: str, time_window: str
) -> None:
    """URLs with different domains or protocol changes are rejected."""
    url = f"{domain}/3/trending/movie/{time_window}"
    assert validate_tmdb_url(url) is False


@pytest.mark.property
@settings(max_examples=100)
@given(url=st.text())
def test_only_exact_two_valid_urls_pass(url: str) -> None:
    """Only the exact two valid URLs pass validation — no others.

    This is the completeness check: validation result must be True if and only if
    the URL is one of the two authorized endpoints.
    """
    expected = url in VALID_URLS
    assert validate_tmdb_url(url) is expected
